# Generated by Django 5.2.17 on 2026-08-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
    ]
