# Generated by Django 5.2.17 on 2026-08-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_user_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshtoken",
            name="created_at",
        ),
    ]
