# Generated by Django 5.2.17 on 2026-08-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_refreshtoken_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salaryslip",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="salaryslip",
            name="updated_at",
        ),
    ]
