# Generated by Django 5.2.17 on 2026-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
