# Generated by Django 5.2.17 on 2026-10-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_backfill_plan_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
